### ISSUE TITLE
plugin.gd at line 65 is missing a plus sign for string concatenation

### ISSUE THREAD

**Issue by Gnumaru** [don-tnowe/godot-subresource-inspector#1]
The '+' right after "ROOT: " at line 65
```gdscript
root_item.set_text(0, "ROOT: "+(edited_object.name if edited_object is Node else edited_object.resource_path))
```
does not exist in the asset downloaded form the assetlib. I have put it there before taking the screenshot bellow.

![image](https://github.com/don-tnowe/godot-subresource-inspector/assets/5783414/4afb6ac7-c520-4f4f-bbf6-b1c59cc590b9)

**Comment by don-tnowe** [comment]
Yes, you're right. I have fixed it now, coming to Asset Lib soon.
